name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: go mod verify
      - run: go test -v ./... -coverprofile=coverage.out
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: go tool cover -func=coverage.out
